import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import NavBar from "./components/layouts/NavBar";

const cairo = Cairo({
  subsets: ["arabic", "latin"],
  weight: ["300","400","500","600","700"], 
  variable: "--font-cairo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${cairo.variable} antialiased`}
      >
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
